import myimage from "../assets/Images/myimage.png";
import css from "../assets/Images/vecteezy_css-programming-language-3d-icon-transparent-background_60194928.png";
import html from "../assets/Images/vecteezy_html-programming-language-3d-icon-transparent-background_60194930.png";
import js from "../assets/Images/vecteezy_javascript-transparent-logo_51336397.png";
import react from "../assets/Images/vecteezy_react-js-programing-language-3d-icon-transparent-background_60194936.png";
import java from "../assets/Images/vecteezy_java-programming-language-3d-icon-transparent-background_60194949.png";
import laravel from "../assets/Images/laravel.png";
import python from "../assets/Images/vecteezy_python-programing-language-3d-icon-transparent-background_60194933.png";
import php from "../assets/Images/vecteezy_php-programming-language-3d-icon-transparent-background_60194947.png";
import nodejs from "../assets/Images/vecteezy_node-js-framework-3d-icon-transparent-background_60194950.png";
import c from "../assets/Images/vecteezy_c-programming-language-3d-icon-transparent-background_60194943.png";
import boot from '../assets/Images/vecteezy_bootstrap-icon-transparent-background_48332157.png';
import git from '../assets/Images/git.png';
import sass from '../assets/Images/sass.png';
import lign from "../assets/Images/lign.png";
import tailwind from '../assets/Images/tailwind.png'
import c2 from '../assets/Images/vecteezy_c-plus-programming-language-3d-icon-transparent-background_60194926.png'
import perl from '../assets/Images/vecteezy_perl-programing-language-3d-icon-transparent-background_60194929.png'
import vscode from '../assets/Images/vecteezy_visual-studio-code-3d-icon-transparent-background_60194939.png'
import mysql from '../assets/Images/mysql.png'
import angular from '../assets/Images/angular-logo.png'
import ts from '../assets/Images/typescript.png'
export default {myimage,c,laravel,html,php,nodejs,python,java,js,react,mysql,ts,angular,css,c2,lign,perl,vscode,sass,git,boot,tailwind}